services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    healthcheck:
      test: bash -c "pg_isready -U postgres -d postgres"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - ./pg-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    networks:
      - backend
    ports:
      - 5432:5432

  gateway_service:
    image: gateway:latest
    build:
      context: .
      dockerfile: ./gateway.dockerfile
      target: release
    container_name: gateway
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend
    command: "/app/bin/gateway"
    ports:
      - 8080:8080

  payment_service:
    image: payment:latest
    build:
      context: .
      dockerfile: ./payment.dockerfile
      target: release
    container_name: payment
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend
    command: "/app/bin/payment"

  loyalty_service:
    image: loyalty:latest
    build:
      context: .
      dockerfile: ./loyalty.dockerfile
      target: release
    container_name: loyalty
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend
    command: "/app/bin/loyalty"

  reservation_service:
    image: reservation:latest
    build:
      context: .
      dockerfile: ./reservation.dockerfile
      target: release
    container_name: reservation
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend
    command: "/app/bin/reservation"
    ports:
      - 6789:8080

networks:
  backend:
    driver: bridge
